# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_2/design_2.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2 || ORIG_REF_NAME==design_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_zynq_ultra_ps_e_0_2/design_2_zynq_ultra_ps_e_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_zynq_ultra_ps_e_0_2 || ORIG_REF_NAME==design_2_zynq_ultra_ps_e_0_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_debug_bridge_0_1/design_2_debug_bridge_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_debug_bridge_0_1 || ORIG_REF_NAME==design_2_debug_bridge_0_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_ps8_0_axi_periph_0/design_2_ps8_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_ps8_0_axi_periph_0 || ORIG_REF_NAME==design_2_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_rst_ps8_0_96M_0/design_2_rst_ps8_0_96M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_rst_ps8_0_96M_0 || ORIG_REF_NAME==design_2_rst_ps8_0_96M_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_xlconstant_0_0/design_2_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_xlconstant_0_0 || ORIG_REF_NAME==design_2_xlconstant_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_system_ila_0_0/design_2_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_system_ila_0_0 || ORIG_REF_NAME==design_2_system_ila_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_auto_pc_0/design_2_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_auto_pc_0 || ORIG_REF_NAME==design_2_auto_pc_0} -quiet] -quiet

# XDC: /home/gabriel/Desktop/go_workspace/vivado_projects/test_network_1/test_network_1.gen/sources_1/bd/design_2/design_2_ooc.xdc
