# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/gabriel/Desktop/go_workspace/vivado_projects/test_network_1/test_network_1.gen/sources_1/bd/design_2/ip/design_2_debug_bridge_0_1/bd_0/ip/ip_0/constraints/axi_jtag.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_4072_axi_jtag_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/gabriel/Desktop/go_workspace/vivado_projects/test_network_1/test_network_1.gen/sources_1/bd/design_2/ip/design_2_debug_bridge_0_1/bd_0/ip/ip_0/bd_4072_axi_jtag_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_4072_axi_jtag_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/gabriel/Desktop/go_workspace/vivado_projects/test_network_1/test_network_1.gen/sources_1/bd/design_2/ip/design_2_debug_bridge_0_1/bd_0/ip/ip_0/constraints/axi_jtag.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_4072_axi_jtag_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/gabriel/Desktop/go_workspace/vivado_projects/test_network_1/test_network_1.gen/sources_1/bd/design_2/ip/design_2_debug_bridge_0_1/bd_0/ip/ip_0/bd_4072_axi_jtag_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_4072_axi_jtag_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
