# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/gabriel/Desktop/go_workspace/vivado_projects/test_network_1/test_network_1.srcs/sources_1/bd/design_2/ip/design_2_system_ila_0_0/design_2_system_ila_0_0.xci
# IP: The module: 'design_2_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/gabriel/Desktop/go_workspace/vivado_projects/test_network_1/test_network_1.gen/sources_1/bd/design_2/ip/design_2_system_ila_0_0/bd_0/bd_074c.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_074c || ORIG_REF_NAME==bd_074c} -quiet] -quiet

# IP: /home/gabriel/Desktop/go_workspace/vivado_projects/test_network_1/test_network_1.gen/sources_1/bd/design_2/ip/design_2_system_ila_0_0/bd_0/ip/ip_0/bd_074c_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_074c_ila_lib_0 || ORIG_REF_NAME==bd_074c_ila_lib_0} -quiet] -quiet

# XDC: /home/gabriel/Desktop/go_workspace/vivado_projects/test_network_1/test_network_1.gen/sources_1/bd/design_2/ip/design_2_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_074c_ila_lib_0 || ORIG_REF_NAME==bd_074c_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/gabriel/Desktop/go_workspace/vivado_projects/test_network_1/test_network_1.gen/sources_1/bd/design_2/ip/design_2_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_074c_ila_lib_0 || ORIG_REF_NAME==bd_074c_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/gabriel/Desktop/go_workspace/vivado_projects/test_network_1/test_network_1.gen/sources_1/bd/design_2/ip/design_2_system_ila_0_0/bd_0/ip/ip_0/bd_074c_ila_lib_0_ooc.xdc

# XDC: /home/gabriel/Desktop/go_workspace/vivado_projects/test_network_1/test_network_1.gen/sources_1/bd/design_2/ip/design_2_system_ila_0_0/bd_0/bd_074c_ooc.xdc

# XDC: /home/gabriel/Desktop/go_workspace/vivado_projects/test_network_1/test_network_1.gen/sources_1/bd/design_2/ip/design_2_system_ila_0_0/design_2_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/gabriel/Desktop/go_workspace/vivado_projects/test_network_1/test_network_1.srcs/sources_1/bd/design_2/ip/design_2_system_ila_0_0/design_2_system_ila_0_0.xci
# IP: The module: 'design_2_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/gabriel/Desktop/go_workspace/vivado_projects/test_network_1/test_network_1.gen/sources_1/bd/design_2/ip/design_2_system_ila_0_0/bd_0/bd_074c.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_074c || ORIG_REF_NAME==bd_074c} -quiet] -quiet

# IP: /home/gabriel/Desktop/go_workspace/vivado_projects/test_network_1/test_network_1.gen/sources_1/bd/design_2/ip/design_2_system_ila_0_0/bd_0/ip/ip_0/bd_074c_ila_lib_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_074c_ila_lib_0 || ORIG_REF_NAME==bd_074c_ila_lib_0} -quiet] -quiet

# XDC: /home/gabriel/Desktop/go_workspace/vivado_projects/test_network_1/test_network_1.gen/sources_1/bd/design_2/ip/design_2_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_074c_ila_lib_0 || ORIG_REF_NAME==bd_074c_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/gabriel/Desktop/go_workspace/vivado_projects/test_network_1/test_network_1.gen/sources_1/bd/design_2/ip/design_2_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_074c_ila_lib_0 || ORIG_REF_NAME==bd_074c_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/gabriel/Desktop/go_workspace/vivado_projects/test_network_1/test_network_1.gen/sources_1/bd/design_2/ip/design_2_system_ila_0_0/bd_0/ip/ip_0/bd_074c_ila_lib_0_ooc.xdc

# XDC: /home/gabriel/Desktop/go_workspace/vivado_projects/test_network_1/test_network_1.gen/sources_1/bd/design_2/ip/design_2_system_ila_0_0/bd_0/bd_074c_ooc.xdc

# XDC: /home/gabriel/Desktop/go_workspace/vivado_projects/test_network_1/test_network_1.gen/sources_1/bd/design_2/ip/design_2_system_ila_0_0/design_2_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
