# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_c_addsub_0_0/design_1_c_addsub_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_c_addsub_0_0 || ORIG_REF_NAME==design_1_c_addsub_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ila_0_0/design_1_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ila_0_0 || ORIG_REF_NAME==design_1_ila_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_zynq_ultra_ps_e_0_3/design_1_zynq_ultra_ps_e_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_zynq_ultra_ps_e_0_3 || ORIG_REF_NAME==design_1_zynq_ultra_ps_e_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_0_2/design_1_proc_sys_reset_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_2 || ORIG_REF_NAME==design_1_proc_sys_reset_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_smartconnect_0_2/design_1_smartconnect_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_smartconnect_0_2 || ORIG_REF_NAME==design_1_smartconnect_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_debug_bridge_0_2/design_1_debug_bridge_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_debug_bridge_0_2 || ORIG_REF_NAME==design_1_debug_bridge_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_vio_0_0/design_1_vio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_vio_0_0 || ORIG_REF_NAME==design_1_vio_0_0} -quiet] -quiet

# XDC: /home/gabriel/Desktop/go_workspace/vivado_projects/test1_MPSoC/test1_MPSoC.gen/sources_1/bd/design_1/design_1_ooc.xdc
