# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/gabriel/Desktop/go_workspace/vivado_projects/test1_MPSoC/test1_MPSoC.srcs/sources_1/bd/design_1/ip/design_1_debug_bridge_0_2/design_1_debug_bridge_0_2.xci
# IP: The module: 'design_1_debug_bridge_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/gabriel/Desktop/go_workspace/vivado_projects/test1_MPSoC/test1_MPSoC.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_0_2/bd_0/bd_05c2.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_05c2 || ORIG_REF_NAME==bd_05c2} -quiet] -quiet

# IP: /home/gabriel/Desktop/go_workspace/vivado_projects/test1_MPSoC/test1_MPSoC.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_0_2/bd_0/ip/ip_0/bd_05c2_axi_jtag_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_05c2_axi_jtag_0 || ORIG_REF_NAME==bd_05c2_axi_jtag_0} -quiet] -quiet

# IP: /home/gabriel/Desktop/go_workspace/vivado_projects/test1_MPSoC/test1_MPSoC.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_0_2/bd_0/ip/ip_1/bd_05c2_bsip_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_05c2_bsip_0 || ORIG_REF_NAME==bd_05c2_bsip_0} -quiet] -quiet

# XDC: /home/gabriel/Desktop/go_workspace/vivado_projects/test1_MPSoC/test1_MPSoC.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_0_2/bd_0/bd_05c2_ooc.xdc

# XDC: /home/gabriel/Desktop/go_workspace/vivado_projects/test1_MPSoC/test1_MPSoC.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_0_2/design_1_debug_bridge_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_debug_bridge_0_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/gabriel/Desktop/go_workspace/vivado_projects/test1_MPSoC/test1_MPSoC.srcs/sources_1/bd/design_1/ip/design_1_debug_bridge_0_2/design_1_debug_bridge_0_2.xci
# IP: The module: 'design_1_debug_bridge_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/gabriel/Desktop/go_workspace/vivado_projects/test1_MPSoC/test1_MPSoC.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_0_2/bd_0/bd_05c2.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_05c2 || ORIG_REF_NAME==bd_05c2} -quiet] -quiet

# IP: /home/gabriel/Desktop/go_workspace/vivado_projects/test1_MPSoC/test1_MPSoC.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_0_2/bd_0/ip/ip_0/bd_05c2_axi_jtag_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_05c2_axi_jtag_0 || ORIG_REF_NAME==bd_05c2_axi_jtag_0} -quiet] -quiet

# IP: /home/gabriel/Desktop/go_workspace/vivado_projects/test1_MPSoC/test1_MPSoC.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_0_2/bd_0/ip/ip_1/bd_05c2_bsip_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_05c2_bsip_0 || ORIG_REF_NAME==bd_05c2_bsip_0} -quiet] -quiet

# XDC: /home/gabriel/Desktop/go_workspace/vivado_projects/test1_MPSoC/test1_MPSoC.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_0_2/bd_0/bd_05c2_ooc.xdc

# XDC: /home/gabriel/Desktop/go_workspace/vivado_projects/test1_MPSoC/test1_MPSoC.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_0_2/design_1_debug_bridge_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_debug_bridge_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
