# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/gabriel/Desktop/go_workspace/vivado_projects/test_network_1/test_network_1.srcs/sources_1/bd/design_2/ip/design_2_rst_ps8_0_96M_0/design_2_rst_ps8_0_96M_0.xci
# IP: The module: 'design_2_rst_ps8_0_96M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/gabriel/Desktop/go_workspace/vivado_projects/test_network_1/test_network_1.gen/sources_1/bd/design_2/ip/design_2_rst_ps8_0_96M_0/design_2_rst_ps8_0_96M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_rst_ps8_0_96M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/gabriel/Desktop/go_workspace/vivado_projects/test_network_1/test_network_1.gen/sources_1/bd/design_2/ip/design_2_rst_ps8_0_96M_0/design_2_rst_ps8_0_96M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_rst_ps8_0_96M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/gabriel/Desktop/go_workspace/vivado_projects/test_network_1/test_network_1.gen/sources_1/bd/design_2/ip/design_2_rst_ps8_0_96M_0/design_2_rst_ps8_0_96M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_rst_ps8_0_96M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/gabriel/Desktop/go_workspace/vivado_projects/test_network_1/test_network_1.srcs/sources_1/bd/design_2/ip/design_2_rst_ps8_0_96M_0/design_2_rst_ps8_0_96M_0.xci
# IP: The module: 'design_2_rst_ps8_0_96M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/gabriel/Desktop/go_workspace/vivado_projects/test_network_1/test_network_1.gen/sources_1/bd/design_2/ip/design_2_rst_ps8_0_96M_0/design_2_rst_ps8_0_96M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_rst_ps8_0_96M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/gabriel/Desktop/go_workspace/vivado_projects/test_network_1/test_network_1.gen/sources_1/bd/design_2/ip/design_2_rst_ps8_0_96M_0/design_2_rst_ps8_0_96M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_rst_ps8_0_96M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/gabriel/Desktop/go_workspace/vivado_projects/test_network_1/test_network_1.gen/sources_1/bd/design_2/ip/design_2_rst_ps8_0_96M_0/design_2_rst_ps8_0_96M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_rst_ps8_0_96M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
