# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/gabriel/Desktop/go_workspace/vivado_projects/axi_interconect/axi_interconect.srcs/sources_1/bd/design_1/ip/design_1_debug_bridge_0_1/design_1_debug_bridge_0_1.xci
# IP: The module: 'design_1_debug_bridge_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/gabriel/Desktop/go_workspace/vivado_projects/axi_interconect/axi_interconect.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_0_1/bd_0/bd_0482.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0482 || ORIG_REF_NAME==bd_0482} -quiet] -quiet

# IP: /home/gabriel/Desktop/go_workspace/vivado_projects/axi_interconect/axi_interconect.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_0_1/bd_0/ip/ip_0/bd_0482_axi_jtag_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0482_axi_jtag_0 || ORIG_REF_NAME==bd_0482_axi_jtag_0} -quiet] -quiet

# IP: /home/gabriel/Desktop/go_workspace/vivado_projects/axi_interconect/axi_interconect.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_0_1/bd_0/ip/ip_1/bd_0482_bsip_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0482_bsip_0 || ORIG_REF_NAME==bd_0482_bsip_0} -quiet] -quiet

# XDC: /home/gabriel/Desktop/go_workspace/vivado_projects/axi_interconect/axi_interconect.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_0_1/bd_0/bd_0482_ooc.xdc

# XDC: /home/gabriel/Desktop/go_workspace/vivado_projects/axi_interconect/axi_interconect.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_0_1/design_1_debug_bridge_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_debug_bridge_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/gabriel/Desktop/go_workspace/vivado_projects/axi_interconect/axi_interconect.srcs/sources_1/bd/design_1/ip/design_1_debug_bridge_0_1/design_1_debug_bridge_0_1.xci
# IP: The module: 'design_1_debug_bridge_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/gabriel/Desktop/go_workspace/vivado_projects/axi_interconect/axi_interconect.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_0_1/bd_0/bd_0482.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0482 || ORIG_REF_NAME==bd_0482} -quiet] -quiet

# IP: /home/gabriel/Desktop/go_workspace/vivado_projects/axi_interconect/axi_interconect.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_0_1/bd_0/ip/ip_0/bd_0482_axi_jtag_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0482_axi_jtag_0 || ORIG_REF_NAME==bd_0482_axi_jtag_0} -quiet] -quiet

# IP: /home/gabriel/Desktop/go_workspace/vivado_projects/axi_interconect/axi_interconect.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_0_1/bd_0/ip/ip_1/bd_0482_bsip_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0482_bsip_0 || ORIG_REF_NAME==bd_0482_bsip_0} -quiet] -quiet

# XDC: /home/gabriel/Desktop/go_workspace/vivado_projects/axi_interconect/axi_interconect.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_0_1/bd_0/bd_0482_ooc.xdc

# XDC: /home/gabriel/Desktop/go_workspace/vivado_projects/axi_interconect/axi_interconect.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_0_1/design_1_debug_bridge_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_debug_bridge_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
