# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/gabriel/Desktop/go_workspace/vivado_projects/test_network_1/test_network_1.srcs/sources_1/bd/design_2/ip/design_2_debug_bridge_0_1/design_2_debug_bridge_0_1.xci
# IP: The module: 'design_2_debug_bridge_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/gabriel/Desktop/go_workspace/vivado_projects/test_network_1/test_network_1.gen/sources_1/bd/design_2/ip/design_2_debug_bridge_0_1/bd_0/bd_4072.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4072 || ORIG_REF_NAME==bd_4072} -quiet] -quiet

# IP: /home/gabriel/Desktop/go_workspace/vivado_projects/test_network_1/test_network_1.gen/sources_1/bd/design_2/ip/design_2_debug_bridge_0_1/bd_0/ip/ip_0/bd_4072_axi_jtag_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4072_axi_jtag_0 || ORIG_REF_NAME==bd_4072_axi_jtag_0} -quiet] -quiet

# IP: /home/gabriel/Desktop/go_workspace/vivado_projects/test_network_1/test_network_1.gen/sources_1/bd/design_2/ip/design_2_debug_bridge_0_1/bd_0/ip/ip_1/bd_4072_bsip_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4072_bsip_0 || ORIG_REF_NAME==bd_4072_bsip_0} -quiet] -quiet

# XDC: /home/gabriel/Desktop/go_workspace/vivado_projects/test_network_1/test_network_1.gen/sources_1/bd/design_2/ip/design_2_debug_bridge_0_1/bd_0/bd_4072_ooc.xdc

# XDC: /home/gabriel/Desktop/go_workspace/vivado_projects/test_network_1/test_network_1.gen/sources_1/bd/design_2/ip/design_2_debug_bridge_0_1/design_2_debug_bridge_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_debug_bridge_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/gabriel/Desktop/go_workspace/vivado_projects/test_network_1/test_network_1.srcs/sources_1/bd/design_2/ip/design_2_debug_bridge_0_1/design_2_debug_bridge_0_1.xci
# IP: The module: 'design_2_debug_bridge_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/gabriel/Desktop/go_workspace/vivado_projects/test_network_1/test_network_1.gen/sources_1/bd/design_2/ip/design_2_debug_bridge_0_1/bd_0/bd_4072.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4072 || ORIG_REF_NAME==bd_4072} -quiet] -quiet

# IP: /home/gabriel/Desktop/go_workspace/vivado_projects/test_network_1/test_network_1.gen/sources_1/bd/design_2/ip/design_2_debug_bridge_0_1/bd_0/ip/ip_0/bd_4072_axi_jtag_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4072_axi_jtag_0 || ORIG_REF_NAME==bd_4072_axi_jtag_0} -quiet] -quiet

# IP: /home/gabriel/Desktop/go_workspace/vivado_projects/test_network_1/test_network_1.gen/sources_1/bd/design_2/ip/design_2_debug_bridge_0_1/bd_0/ip/ip_1/bd_4072_bsip_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4072_bsip_0 || ORIG_REF_NAME==bd_4072_bsip_0} -quiet] -quiet

# XDC: /home/gabriel/Desktop/go_workspace/vivado_projects/test_network_1/test_network_1.gen/sources_1/bd/design_2/ip/design_2_debug_bridge_0_1/bd_0/bd_4072_ooc.xdc

# XDC: /home/gabriel/Desktop/go_workspace/vivado_projects/test_network_1/test_network_1.gen/sources_1/bd/design_2/ip/design_2_debug_bridge_0_1/design_2_debug_bridge_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_debug_bridge_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
