# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/gabriel/Desktop/go_workspace/vivado_projects/axi_interconect/axi_interconect.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_0_1/bd_0/ip/ip_1/constraints/bsip.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_0482_bsip_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/gabriel/Desktop/go_workspace/vivado_projects/axi_interconect/axi_interconect.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_0_1/bd_0/ip/ip_1/bd_0482_bsip_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_0482_bsip_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/gabriel/Desktop/go_workspace/vivado_projects/axi_interconect/axi_interconect.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_0_1/bd_0/ip/ip_1/constraints/bsip.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_0482_bsip_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/gabriel/Desktop/go_workspace/vivado_projects/axi_interconect/axi_interconect.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_0_1/bd_0/ip/ip_1/bd_0482_bsip_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_0482_bsip_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
